[project]
name = "globussoft-data-science-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi[standard]>=0.136.3",
    "insightface>=1.0.1",
    "lxml>=6.1.1",
    "onnxruntime>=1.26.0",
    "opencv-python-headless>=4.13.0.92",
    "pandas>=3.0.3",
    "requests>=2.34.2",
    "scikit-learn>=1.8.0",
]
